# Generated by Django 4.0.3 on 2022-03-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('brand', models.CharField(max_length=120)),
                ('img', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=90)),
                ('desc', models.TextField(max_length=500)),
                ('currently_being_poured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
