# Generated by Django 4.0.3 on 2022-03-14 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_beer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='user',
        ),
    ]
